# Primeros Pasos con Python

## Operadores <br>

Con Python (y con cualquier lenguaje básico de programación) podemos realizar operaciones aritméticas básicas, como si se tratase de una calculadora.

In [54]:
4 + 2

6

In [55]:
4 / 3 

1.3333333333333333

In [3]:
4 ** 2

16

In [68]:
4 % 2

0

Podemos crear variables, para asignarles números. Esto hace que, por detrás, el ordenador reserve un espacio de su memoria y le asigne como identificador el nombre que le indiquemos. A diferencia de otros lenguajes, no hay que indicar el tipo de dato del que se trata. 

In [5]:
a = 4
a + 1

5

In [6]:
b = 5 
a * b

20

In [7]:
type(b)

int

In [11]:

c=5/2
print(type(c))
round(c)
print(round(c))

<class 'float'>
2


In [56]:
from math import sqrt
print(sqrt(16))
help(math)

4.0
Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    copysign(x, y, /)
        Return a float with the magnitude (absolute value) of x but the sign of y.

In [12]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



# Variables <br>

Manejar números está bien, pero en la vida real, también nos interesa manejar texto. Imaginad por ejemplo, una página web en la que nos piden un usuario y contraseña. O en los sistemas más avanzados de inteligencia artificial, cuando un usuario interactúa con un asistente como Alexa o Google, en que según lo que ha entendido, escribe la frase y la busca en Google.

In [7]:
usuario = "javier_advani"
password = '12345' # distinguimos una cadena de texto de un número cuando lo ponemos entre comillas simples o dobles.

Juguemos con las cadenas de texto (strings en inglés)

In [8]:
usuario +  password

'javier_advani12345'

In [9]:
usuario * 2

'javier_advanijavier_advani'

In [11]:
print("Mi usuario es: "+usuario+" y la contraseña es: "+password)

Mi usuario es: javier_advani y la contraseña es: 12345


In [13]:
usuario.upper()

'JAVIER_ADVANI'

In [14]:
pais="ESPAÑA"
pais.lower()

'españa'

In [26]:
# Existe otro tipo de datos que no hemos visto aún, y que también es muy utilizado: el booleano. Los ordenadores, de una manera muy simplificada, funcionan por dentro gracias a que miles de pequeños interruptores, parecidos a los que tenemos por casa, se activan o desactivan constantemente. La forma más simple de representar y modificar los valores, es almacenando un '1' lógico, si está encendido (true) o un '0' si está apagado (false). 
#Estos "interruptores" nos van a servir para poder hacer operaciones más complejas en un futuro. 

soy_humano = True 
es_perro_humano = not soy_humano # con este operador de negación, estoy indicando que quiero que mi perro sea lo contrario a mí. Que su interruptor "humano" esté "apagado" cuando yo estoy activado.


print("soy humano? -"+str(soy_humano))
print("y mi perro, es humano? -"+str(es_perro_humano))

soy humano? -True
y mi perro, es humano? -False


In [28]:
soy_humano= False
print("soy humano? -"+str(soy_humano))
print("y mi perro, es humano? -"+str(es_perro_humano))

soy humano? -False
y mi perro, es humano? -True


In [29]:
# Otros operadores útiles...

5 > 4

True

In [31]:
200 < 100

False

In [35]:
200 == (100+100)

True

In [34]:
200 != 300

True

In [50]:
# Otro tipo de dato básico que va a ser de interés, es el array, o vector. Se trata de una sucesión de elementos. Por comodidad y eficiencia, a veces nos interesa tener una cantidad de valores en una única variable

calificaciones_alumnos = [5.6 , 7.2 , 3.5, 9.2, 4, 6.1]
nombres_alumnos = ['Juan', 'Gloria', 'Pepe', 'Andrea', 'Jose', 'Julia']

In [51]:
# veamos la primera calificación del array

calificaciones_alumnos[0]

5.6

In [52]:
# cuál es la del último alumno?

calificaciones_alumnos[-1] 

6.1

In [53]:
# cuál es la mejor calificación obtenida en la clase?
print("la mejor calificación es: "+str(max(calificaciones_alumnos)))
# la peor calificación?
print("la peor calificación es: "+str(min(calificaciones_alumnos)))

la mejor calificación es: 9.2
la peor calificación es: 3.5


In [57]:
# Pero esta forma es algo caótica para identificar a cada alumno... tendríamos que buscar el índice de cada calificación y buscar después en los nombres

indice_maximo = calificaciones_alumnos.index(max(calificaciones_alumnos))
nombres_alumnos[indice_maximo]

'Andrea'

In [15]:
# Otra forma más eficiente de representar este par de datos en Python (nombre de cada alumno y su nota) es usando diccionarios

calificaciones_mejoradas = {'Pepe':6, 'Julia':9.2, 'Juan':4}
calificaciones_mejoradas.get("Pepe")


6

In [14]:
max(calificaciones_mejoradas, key=calificaciones_mejoradas.get)

'Julia'

In [15]:
# Existen otras estructuras de datos, como las listas, tuplas, o matrices, que pueden ser útiles en muchos contextos diferentes.

# La tupla es un array inmutable (que no se puede variar). Imaginemos por ejemplo, que estamos jugando con coordenadas, y siempre queremos guardar una de referencia

ref_coord = (7,2) 

In [18]:
ref_coord[0] = 6 # al intentar variar su valor, nos dice que no es posible

TypeError: 'tuple' object does not support item assignment

In [57]:
# Si queremos procesar GRANDES cantidades de datos, una de las estructuras más utilizadas en programación, son las matrices (en python se conocen como arrays)
# Existen numerosas librerías, la más extendida es numpy

import numpy as np

matrix_aux = [[1,2,3],
     [4,5,6]]

m = np.array(matrix_aux)

print(m)

[[1 2 3]
 [4 5 6]]


In [65]:
unos=np.ones((4, 4))
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [66]:
ceros=np.zeros((6,6))
print(ceros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [25]:
# Hasta ahora estamos limitándonos a manejar datos y cálculos aritméticos, pero queremos también aprender a establecer reglas, instrucciones, incluso corregir o generar información a medida que vamos ejecutando nuestro programa. 

# Condicionales 
#no existen switch, tenemos que utilizar diccionarios
nota_final=9.2

if 0<=nota_final<5:
    print("suspenso")
elif 5<=nota_final<=10:
    print("aprobado")
else: 
    print("nota errónea")

aprobado


In [1]:
meses = ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio"]

for mes in meses:
    print(mes)
print("\n")
for individuo in calificaciones_mejoradas:
    print(individuo+", "+str(calificaciones_mejoradas.get(individuo)))
    


Enero
Febrero
Marzo
Abril
Mayo
Junio
Julio




NameError: name 'calificaciones_mejoradas' is not defined

In [2]:
type(meses)

list

In [3]:
i=4
type(i)

int

## Funciones 

In [16]:
def saludar(who="Javier"):
    print("Hola,", who)
saludar("Juan")
saludar()


Hola, Juan
Hola, Javier


## Challenge: FizzBuzz <br>

Imagine the scene. You are eleven years old, and in the five minutes before the end of the lesson, your Maths teacher decides he should make his class more “fun” by introducing a “game”. He explains that he is going to point at each pupil in turn and ask them to say the next number in sequence, starting from one. The “fun” part is that if the number is divisible by three, you instead say “Fizz” and if it is divisible by five you say “Buzz”. So now your maths teacher is pointing at all of your classmates in turn, and they happily shout “one!”, “two!”, “Fizz!”, “four!”, “Buzz!”... until he very deliberately points at you, fixing you with a steely gaze... time stands still, your mouth dries up, your palms become sweatier and sweatier until you finally manage to croak “Fizz!”. Doom is avoided, and the pointing finger moves on. So of course in order to avoid embarrassment in front of your whole class, you have to get the full list printed out so you know what to say. Your class has about 33 pupils and he might go round three times before the bell rings for breaktime. Next maths lesson is on Thursday. Get coding! Write a program that prints the numbers from 1 to 100. But for multiples of three print “Fizz” instead of the number and for the multiples of five print “Buzz”. For numbers which are multiples of both three and five print “FizzBuzz”.

1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz 16 17 Fizz 19 Buzz ... etc up to 100 #Additional discussion points for the Retrospective • Is the code you have written clean? Are there any smells? • Did you refactor throughout or do it all at the end? • What if a new requirement came along that multiples of seven were “Whizz”? Could you add that without editing the existing code? (Cue discussion of the Open- Closed Principle) Kata: FizzBuzz 125 #Ideas for after the Dojo • When you’ve got it all working for “Fizz” and “Buzz”, add “Whizz” for multiples of seven • Then add “Fizz” also for all numbers containing a 3 (eg 23, 53) #Contexts to use this Kata I find this an excellent kata for introducing beginners to TDD. It’s pretty straightforward to choose the order of test cases, work in small steps, and complete the whole exercise still leaving time for a decent retrospective.

In [44]:
def isFizz(num):
    return num%3==0 
def isBuzz(num):
    return num%5==0
def isWhizz(num):
    return num%7==0

def processNumber(num):
    result_word=""
    if(isFizz(num)):
        result_word+="Fizz"
    if(isBuzz(num)):
        result_word+="Buzz"
    if(isWhizz(num)):
        result_word+="Whizz"
    return result_word

def generateFizzBuzz_old(last_number):
    happy_numbers = range(1, last_number)
    for number in happy_numbers:
        print(str(number) if processNumber(number)=="" else processNumber(number))
#processNumber(15)
#generateFizzBuzz(32)


#version mejorada

def generateFizzBuzz(last_number):
    happy_numbers = range(1, last_number+1)
    result = [(str(number) if processNumber(number)=="" 
               else processNumber(number)) for number in happy_numbers]
    print(result)

generateFizzBuzz(105)

['1', '2', 'Fizz', '4', 'Buzz', 'Fizz', 'Whizz', '8', 'Fizz', 'Buzz', '11', 'Fizz', '13', 'Whizz', 'FizzBuzz', '16', '17', 'Fizz', '19', 'Buzz', 'FizzWhizz', '22', '23', 'Fizz', 'Buzz', '26', 'Fizz', 'Whizz', '29', 'FizzBuzz', '31', '32', 'Fizz', '34', 'BuzzWhizz', 'Fizz', '37', '38', 'Fizz', 'Buzz', '41', 'FizzWhizz', '43', '44', 'FizzBuzz', '46', '47', 'Fizz', 'Whizz', 'Buzz', 'Fizz', '52', '53', 'Fizz', 'Buzz', 'Whizz', 'Fizz', '58', '59', 'FizzBuzz', '61', '62', 'FizzWhizz', '64', 'Buzz', 'Fizz', '67', '68', 'Fizz', 'BuzzWhizz', '71', 'Fizz', '73', '74', 'FizzBuzz', '76', 'Whizz', 'Fizz', '79', 'Buzz', 'Fizz', '82', '83', 'FizzWhizz', 'Buzz', '86', 'Fizz', '88', '89', 'FizzBuzz', 'Whizz', '92', 'Fizz', '94', 'Buzz', 'Fizz', '97', 'Whizz', 'Fizz', 'Buzz', '101', 'Fizz', '103', '104', 'FizzBuzzWhizz']
